# Generated by Django 3.0.2 on 2020-02-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=20)),
                ('doc_email', models.EmailField(max_length=254)),
                ('specialisation', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
            ],
        ),
    ]
